package com.project.AlphaSpringBot.botapi;

public enum BotState {
    START,
    PROCESSING,
    EAT_START,
    EAT_NAME,
    EAT_CALORIES,
    EAT_FATS,
    EAT_PROTEINS,
    EAT_CARBOHYDRATES,
    EAT_WEIGHT,
    EAT_CLOSE,
    PUKE_START,
    PUKE_DELETE,
    INFO,
    PUKE_INPUT, CALORIES, CALORIES_START, CALORIES_STOP, INFO_TOTAL, INFO_TODAY
}
